# Generated by Django 5.1.7 on 2025-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('certificate_file', models.ImageField(upload_to='certificates/')),
                ('issued_date', models.DateField()),
            ],
        ),
    ]
